const CONTEXT = `
Audience: The target audience is 7-15 years old.
Real Data: Stories must incorporate real data about exoplanets and space, staying grounded in science.
Interactivity: At key moments, the reader is asked for input or choices to shape the story.
Descriptive and Immersive: Use vivid, descriptive language to create engaging, immersive experiences.
Educational: Weave educational insights into the fun narrative.
Suspense and Engagement: End each section with a catchy phrase to maintain engagement.
Response Length:
	•	The first response will be around 200 words.
	•	Follow-up responses (after user input) will be limited to 80 words.
Focus: Stick to the story and continue it without diverging based on unrelated user inputs.
Data Source: The story should use only data provided in the context, avoiding external resources.
Fun in the Foreground: The story should keep the fun side as a priority.
Do not use non-alphanumeric characters in your response.
In your response, you must include the following sections:
Information Data:
"
Exoplanets are planets that orbit stars beyond our solar system. While most exoplanets orbit stars, some, known as rogue planets, do not. Over 5,600 exoplanets have been confirmed so far, though many more are believed to exist. Most discovered exoplanets are located within thousands of light-years from our solar system, with Proxima Centauri b, the closest known exoplanet, being 4 light-years away.

Exoplanets vary in composition, ranging from rocky worlds like Earth to gas giants like Jupiter. Some planets are covered in water or ice, while others are composed primarily of carbon or iron. Scientists have discovered extreme types of exoplanets, such as lava-covered planets and massive gas giants with the density of Styrofoam.

How Are Exoplanets Found?
Exoplanets are usually found using two main methods: the transit method and radial velocity method. The transit method involves detecting the slight dimming of a star’s light when a planet passes in front of it. The radial velocity method measures a star’s wobble caused by the gravitational pull of an orbiting planet. Other methods include direct imaging, gravitational microlensing, and astrometry.

Exoplanet Naming
Exoplanets are named after the telescope or survey that discovered them, followed by a catalog number and a lowercase letter representing the order of discovery. The first planet found in a system is designated “b,” and subsequent discoveries are labeled “c,” “d,” and so on.

Confirmed vs. Candidate Exoplanets
An exoplanet is considered “confirmed” after being observed by at least two other telescopes, while a “candidate” is a planet-like object awaiting verification. Thousands of candidates are still awaiting confirmation.

NASA’s Exoplanet Telescopes
NASA has used various telescopes to discover exoplanets, such as the Kepler Space Telescope, which discovered thousands of exoplanets during its mission from 2009 to 2018. Other key instruments include the Spitzer Space Telescope and the Transiting Exoplanet Survey Satellite (TESS). The James Webb Space Telescope is expected to provide more detailed observations of exoplanets, including their atmospheres.

Notable Exoplanets
Kepler-16b was the first planet discovered with two suns, similar to Tatooine in “Star Wars.” Kepler-452b, discovered in 2015, is often called Earth’s “older cousin” due to its similarities. Other notable exoplanets include KELT-9b, which is hotter than many stars, and WASP-12b, a planet being devoured by its parent star.

Future of Exoplanet Exploration
While we cannot yet travel to exoplanets, future telescopes will continue the search for Earth-like planets and study their atmospheres to determine if they could support life. Direct imaging of exoplanets is becoming more common, though it remains challenging due to the faint light of distant planets compared to their stars. Scientists are optimistic about finding signs of life beyond Earth in the coming decades.

These colorful light shows were generated by solar storms and provide a vivid demonstration of activity on the Sun affecting the Earth. The pummeling experienced by our home planet is an example of our one-way relationship with the Sun: it can have a noticeable effect on the Earth, but the Earth has a negligible effect on the Sun. Further afield in the galaxy, this isn’t always the case. In a few other systems, planets can have a big effect on their star, changing their looks in surprising ways.

WASP-18b is an example of a hot Jupiter, with a mass about ten times that of Jupiter and an orbit that is less than 24 hours long. The host star, WASP-18, is estimated to have an age that lies between about 500 million and 2 billion years, relatively young by astronomical standards.

Younger stars tend to be more active, with stronger magnetic fields, larger flares, and more intense X-ray emission than their older counterparts. Magnetic activity, flaring, and X-ray emission are linked to the stellar rotation, which generally declines with age. However, when astronomers took a long look with Chandra at WASP-18, they didn’t detect any X-rays. Using established relations between the magnetic activity and X-ray emission of stars and their age indicates that WASP-18 is about 100 times less active than it should be at its age.

The researchers argue that tidal forces from the gravitational pull of the massive planet – similar to those the Moon has on Earth’s tides but on a much larger scale – may have disrupted the magnetic field of the star. The strength of the magnetic field depends on the amount of convection in the star. Convection is the process where hot gas stirs the interior of the star.

The planet’s gravity may cause motions of gas in the interior of the star that weaken the convection, causing the magnetic field to weaken and activity to decline. This causes the appearance of premature aging in the star. WASP-18 is thought to have a shallow convection zone, making it unusually susceptible to tidal effects.

In some cases, where they orbit a different type of star to WASP-18, the effect of hot Jupiters can be flipped and they can make a star appear younger than it really is. In the cases of HD 189733 and CoRoT-2a, the presence of the planet appears to have increased the amount of activity in the star. In these cases, the stars have much deeper convection zones than WASP-18, and tidal effects have little influence on convection and hence on the star’s dynamo. Instead, the planets may be speeding up their star’s rotation, leading to a more powerful dynamo and more activity than expected for the star’s age. In these cases, having a companion makes the star act younger than it really is. That makes sense for people and, in a few cases, for stars.

In such systems, what effect does the star have on its planet? In the cases of HD 189733 and CoRoT-2a, strong X-rays and ultraviolet radiation from the active star are evaporating the atmospheres of the planet. For HD 189733, astronomers estimate the planet is losing 100 to 600 million kilograms per second, and for CoRoT-2a, astronomers estimate the planet is losing about 5 billion kilograms per second. For WASP-18, with much weaker X-ray emission and ultraviolet radiation, there is much less evaporation of the nearby planet’s upper atmosphere than there would be if the star was more active. In effect, the planet is protecting itself. Its gravity causes the nearby star to be less active, and that causes the planet to be struck with less damaging radiation. HD 189733b and CoRoT-2b, on the other hand, are behaving in a self-destructive manner.

Talk of planet destruction isn’t necessary for our present-day solar system, where the planets are much farther away from the Sun than hot Jupiters are. However, that won’t always be the case. A few billion years in the future, the Sun will dramatically expand in size when it becomes a red giant. Our oceans will boil away, never to return, and what’s left of the Earth may end up spiraling in towards the Sun. We don’t know the exact fate of our home planet, but it is clear that our aurora-viewing days are numbered.

A Star Is Born
It all begins with an unimaginably cold cloud. This cloud contains the seeds of whole new worlds – stars and planets about to be born. Molecules of hydrogen and helium gas, which normally zip around at high speeds, slow down and clump together because of gravity. Tiny grains of silicates, iron, and carbon-rich material — together classified simply as “dust” — send some of the gas’s energy back out into space, making the cloud even colder. The dust grains spiral into the central knot of matter, like water running down a drain.

As this pocket of the cloud contracts and thickens, a bright, hot ball begins to form at the center as more gas and dust are pulled in. Gravity is waging a battle against the pressure of gas and magnetic fields, and gravity is winning.

While the infant star takes shape, the material spiraling inward flattens into a pancake-like structure known as an accretion disk. The gravitational tugs of the galaxy’s billions of stars may have accelerated and shocked the gas. Or, maybe two clouds are bumping into each other, causing pockets of gas to coalesce. But sometimes, the catastrophic explosion of a massive star drives strong winds of material into a star-forming cloud — a death resulting in a new birth.

Mysteriously, in our galaxy and probably most others, the likeliest type of star to form is almost too small to sustain itself. Red dwarfs, which can be between one-thirteenth to one-half the mass of the Sun, represent three-quarters of the stars in the Milky Way. Any smaller than this, and hydrogen cannot fuse in its core – the dominant process powering most stars. Red dwarf stars burn so slowly that their lifetimes will be longer than that of the present-day universe.

Sun-like stars are more rare, although they still represent 8 percent of the galaxy. Most rare are the very massive stars, which can weigh as much as 150 suns and only live a few million years. “Those stars are so big, so luminous, and so short-lived, that astronomers are observing these stars in their pulsating, mass-ejecting death throes, while their low-mass stellar siblings are still in the process of forming,” Mamajek said.

A young star is called a “protostar” until it can power itself with hydrogen fusion reactions, and high temperature is crucial to that transition. As matter falls in faster and faster, and the ball of gas at the center gets smaller and more compact, the tug-of-war between gravity and other pressures heats up the infant star. Even hundreds of thousands of degrees is not enough. The core of the star must get to about 10 million degrees before it becomes a hydrogen-burning machine. To be a bona fide star, it must spontaneously fuse hydrogen atoms to form helium, releasing enormous amounts of energy. This energy stabilizes the star’s core, such that it stops contracting. This whole process can take about 40 million years.

‘Raining’ Stars
The same process may be happening in dozens, hundreds, or even thousands of places in the same molecular cloud, becoming a glittering stellar nursery. “It’s like rain in a cloud on Earth,” said Eric Mamajek, deputy program scientist of NASA’s Exoplanet Exploration Program. “If you’ve got the combination of physical conditions to form a drop of rain, chances are you’re next to parcels of gas that have similarly ripe conditions right for producing lots and lots and lots of rain.”

In this way, molecular clouds are like Earth clouds, and the raindrops are like stars. The gas from these clouds can collapse and fragment, forming big batches of baby stars. So, stars tend to form in big groups.

NEWS FLASH: A stellar nursery
Cygnus X is one of the most active regions in the Milky Way, hatching baby stars. Some 4,500 light-years away, thousands of stars are being cradled in a violently turbulent cloud of gas and dust. NASA’s Spitzer Space Telescope captured this image in infrared light that reveals cavities in the cloud, carved out by the violent outbursts of massive stars. The radiation and winds from these massive stars can rip star-forming material apart, but also trigger the birth of new stars. In this image, the color green highlights dust tendrils, while red shows possibly cooler types of dust and ionized gas from nearby massive stars.

Scientists say most stars formed in large regions like Cygnus X, and then move away from each other over time. Our Sun may have similarly grown up close to other new stars before it left the nest.

From Cloud to Disk
The newborn star is a feisty baby, shooting out violent jets of magnetically accelerated material as it gets nourishment from the gas and dust whirling around it. Like a blob of pizza dough flattening out as a chef spins it, this material condenses into a flat disk. That “dough” has a preferred direction inherited from the collapse of the cloud. That same spin will remain with the system for its entire life unless another star system gets close enough to interact with it.

At about 100,000 years, the cloud starts to thin out enough to reveal two distinct structures: a newborn star and a fluffy, diffuse disk of gas and dust.

Scientists who study these very young systems are looking for features in the disk that indicate places where planets may be forming. At first, the gravity of a baby planet will warp material around it into a spiral shape. But as the planet grows bigger, it will carve out a larger gap in the disk.

Yasuhiro Hasegawa, a researcher at NASA’s Jet Propulsion Laboratory, has been studying one famous example: HL Tau, using the Atacama Large Millimeter/submillimeter Array (ALMA) – a group of radio telescopes in Chile. Gaps in this disk, making it look like rings, may be the footprints of baby planets, as research has revealed in the last couple of years. “This discovery was a big leap in our field,” he said.

A more mysterious system is called TW Hydrae, the closest star we know that still has a gas-rich protoplanetary disk (although it is still 175 light-years away). ALMA has also revealed striking images of this disk with gaps that suggest planetary formation. However, the gaps appear in vastly different places depending on which wavelength of light was used – radio waves detected by ALMA tell a different story than optical light from the European Southern Observatory’s Very Large Telescope. “The question is, why are there differences? What’s that coming from?” said Hannah Jang-Condell of the University of Wyoming. “It’s a real puzzle.”

NASA’s James Webb Space Telescope, planned for a 2021 launch, could teach us much more about disks like these by measuring the heat radiation coming from them in infrared light.

Planetary ‘Crumbs’
The whole system is still mostly hydrogen and helium, with about 100 times more gas than dust in the disk. The dust will be critical to forming planets, containing elements such as carbon and iron.

“Planets are essentially the crumbs that don’t end up in the star,” said Joel Green, scientist at Space Telescope Science Institute.

NEWS FLASH: Gluttonous young star
Changes in stars and their disks often happen over much longer periods than human lifetimes. But the young star FU Orionis has shown marked mood swings in a matter of decades, offering a rare look at a planetary nursery under construction.

In 1936, astronomers observed FU Orionis becoming 100 times brighter than normal – energy emitted as the star gobbled up gas and dust from its surrounding disk. More recently, astronomers used NASA’s Stratospheric Observatory for Infrared Astronomy (SOFIA) and the Spitzer Space Telescope to check in on the young star. They found that the star has been eating the innermost part of its disk, and that the star’s overall brightness has been slowly fading since 1936.

The initial flare-up seen more than 80 years ago would have altered the chemical composition of material swirling closest to the star. If that material one day forms planets, the fates of those worlds will be altered by FU Orionis’s snacking.

Collisions, Collisions
A very young disk around a star contains mostly gas with dust – no bigger than grains of sand – swirling around in it. The baby star is still throwing out extremely hot winds, dominated by positively charged particles called protons and neutral helium atoms. A lot of the material from the disk is still falling on the star. But small groups of lucky dust particles are crashing into one another, clumping into larger objects. Planets will form from less than 1 percent of the mass of the disk.

“We look at our solar system now, and we’re just seeing the stuff that has survived that initial process,” Mamajek said. “There might have been earlier generations of planets that actually migrated in and were absorbed by the Sun, in just the first few million years of our history.”

The presence of gas helps particles of solid material stick together. Dust clumps become pebbles, pebbles become larger rocks that grind together to enlarge. Some break apart, but others hold on. These are the building blocks of planets, sometimes called “planetesimals.”

A different kind of adventure in making planets is called “gravitational instability.” When pockets of gas in the protoplanetary disk become overly dense, they can cool down and contract rapidly into objects ranging from comets to planets. This can only happen far away from the star so that the star’s own gravity doesn’t rip these objects apart. Rather than beginning as grains and accumulating material slowly over millions of years, bodies born from instability are thought to reach their full size within a few thousand years.

The giant planets of our solar system were once thought to have formed this way, through the collapse of gas in the disk. Today, scientists think it’s more likely this is the story of how planets much more massive than Jupiter formed around other stars. Some brown dwarfs, objects too big to be planets but too small to fuse hydrogen and become stars, may have been born this way, too.

In our own solar system, small icy bodies in the Kuiper Belt, where Pluto orbits, may have emerged directly from the protoplanetary disk as well. These so-called “Cold Classical Belt” objects could have formed quickly from the collapse of rock and ice.

Temperature Matters
Where the disk is colder, far enough from the star that water can freeze, tiny fragments of ice hitch a ride with dust. Dirty snowballs can amass into giant planetary cores. These colder regions also allow gas molecules to slow down enough to be drawn onto a planet. This is how Jupiter, Saturn, Uranus, and Neptune – the gas giants of our solar system – are thought to have formed: a rock-ice core grabbing gas out of the disk and forming the wondrous swirling layers of gas of the planets we see today. Jupiter and Saturn are thought to have formed first, and quickly – within the first 10 million years of the solar system.

In the warmer reaches of the disk, closer to the star, rocky planets take shape after the icy giants form – and there’s not a lot of gas left for the terrestrial planets to snag. Planets that are rocky like Mercury, Venus, Earth, and Mars may take tens of millions of years to form after the birth of the star. The details of exactly where planets prefer to form in disks are still a mystery – and an ongoing area of research.

“You want a sweet spot where things collapse easily, but not so far out that the material is so spread out,” Green said.

NEWS FLASH: Shhhh….Planet Formation in Progress
There have been very few examples of baby planets caught in the act of forming in a disk around a star. But Miriam Keppler and André Müller at the Max Planck Institute for Astronomy in Germany each led teams that captured rare images of young planet PDS 70b, using the European Southern Observatory’s Very Large Telescope in Paranal, Chile. They announced the discovery in 2018.

A gas giant, PDS 70b is already more massive than Jupiter and could still be growing. Its gravity carves out a large gap in its disk and orbits its star roughly at the same distance as Uranus in relation to our Sun. Because material continues to fall on PDS 70b from the disk, releasing energy, the young PDS 70b is hotter than any planet in our solar system at 1,800 degrees Fahrenheit (1,000 degrees Celsius).

The PDS 70 system is 5 million years old — only a little over 0.1 percent the age of Earth. Although the planet is in some sense newborn, Müller thinks of it more like a 14-year-old. “It’s not fully grown up,” he said. “It’s still a little bit wild, but starting to get mature.”

Moving Around
Based on just an image of baby planets in a protoplanetary disk, it is impossible to determine what the system will look like as it matures. “Is disk destiny? Probably not,” said Heather Knutson, professor at Caltech in Pasadena. “Growing planets don’t stay put. They move around. They interact with each other, and with the gas disk, in a way that can be quite random and messy.”

The tail end of the formation of the solar system, between about 50 million and 500 million years after the Sun formed, was particularly turbulent for our solar system. This was when the giant planets of the outer solar system reorganized themselves. Based on careful study of the distribution of bodies in the asteroid belt between Mars and Jupiter and the Kuiper Belt beyond Neptune, we now know there must have been a period when the orbital positions of Jupiter and Saturn led to a tug-of-war. This shuffling may have scattered Uranus and Neptune out to their current orbits and bombarded Earth with debris.

“The late phases of planet formation were a really gradual process as planets slowly shifted in their orbits,” said Avi Mandell, researcher at NASA’s Goddard Space Flight Center. “We believe those small changes may have eventually led to a huge event of scattering between planets.”

But what exactly caused it? A hotly debated question in planetary science is how a special alignment, or “resonance,” between the orbits of Jupiter and Saturn could have changed their positions, as well as those of Uranus and Neptune.

We still have a few groups of small objects that were likely flung around as Jupiter and Saturn tumbled through their youth. The asteroid belt between Mars and Jupiter contains small rocky “planet wannabes” that never got to reach their potential because of interference from Jupiter’s gravity, Knutson said. The Kuiper Belt, which contains Pluto, was probably shaped by this process of planetary shuffling, too, especially because of Neptune’s scattering. There’s a whole other outpost even farther afield: the Oort Cloud, a sparse but vast sphere of comets circling the Sun. The Oort Cloud begins roughly 200 billion miles (300 billion kilometers) away from the Sun and may extend as far as 9 trillion miles (10 trillion kilometers) from our star.

Scientists are looking at other star systems at various ages to search for evidence of similar processes happening elsewhere. “By combining the archaeology of our own solar system with the formation of planets in other systems, we can create a holistic picture of how we came to have the planetary architecture we see today,” Mandell said.

A Turbulent Time
After the gas of the disk has been grabbed up by rocky planets or dissipated into the vastness of space, the planets don’t sit still. In such a young system, planets or planetary building blocks called “protoplanets” may be orbiting on collision courses with each other, and the absence of gas makes moving around easier than ever.

Big planets may kick smaller bodies into the star or out of the system entirely. This is one possible explanation for large, lonely bodies called “rogue planets” that have been found without stars. The recent mysterious visitor to our own solar system, a small comet named ’Oumuamua, is thought to have been ejected from a different star system.

NEWS FLASH: Evaporating Planet
One revelation that made scientists rethink their ideas about a planet’s life story is that our galaxy has many “hot Jupiters.” These are planets found in other star systems, not our own, that are about the same size as Jupiter or larger but orbit much closer to their host stars – worlds where one “year” can be less than two days.

In 2017, scientists announced the discovery of KELT-9b, a planet hotter than most stars, where temperatures can reach 7,800 degrees Fahrenheit. It was discovered using one of the two ground-based telescopes called KELT, or Kilodegree Extremely Little Telescope. By 2018, evidence had emerged that the star’s gravity is actually ripping the planet apart.

KELT-9b and other hot Jupiters could not have formed so close to their stars, or else their building blocks would have been ripped apart long ago. Only in colder, farther regions of a protoplanetary disk could such immense planets take shape. These gas giants must have migrated toward the star only after reaching their immense sizes.

Settling Down
At approximately 100 million to 1 billion years old, planets tend to settle down in their orbits and stars don’t flare up as much. Our own solar system, about 4.5 billion years old, is the model for this idea of planetary “middle age.” Mandell thinks of our planetary system as about 45 to 50 years old, when scaled down to a human lifetime.

But by studying exoplanets, the planets beyond our solar system, scientists know that our solar system is not the only way a planetary system can look in this comfortable age of life.

One star that recently became famous for its seven Earth-size rocky planets, TRAPPIST-1, formed somewhere between 5.4 billion and 9.8 billion years ago, safely older than our solar system. TRAPPIST-1, at only about 9% the size of our Sun, is an extremely faint M-dwarf star. All of its planets huddle extremely close together — all within the orbit of Mercury. Because the star’s energy output is so low, its farthest planet, TRAPPIST-1 h, may be a ball of ice, even though it makes one revolution around its star in less than 19 days. Another planet in this system, called TRAPPIST-1 e, is especially similar to Earth in the amount of starlight its surface receives, even though one “year” there is 6.1 days.

Hot Jupiters, about the same size as Jupiter or larger, orbiting much closer to their host stars and experiencing scorching hot temperatures, are nowhere to be found in our solar system. We could have had a hot Jupiter that got swallowed by the Sun early on, but plenty have survived in other systems – even older ones. Two examples are HAT-P-65 b, which scientists calculate to be 5.5 billion years old, and HAT-P-66 b, with an estimated age of 4.7 billion years. Other exotic kinds of planets around other stars include “super-Earths” – large rocky planets up to 10 times the mass of Earth – and small gaseous planets called “mini-Neptunes.”

The Sun may wipe out life on Earth even before it swells up to reach its red giant phase. Over the next couple of billion years, the increasing amounts of energy Earth will receive from the aging, expanding Sun will warm its atmosphere. The hotter the atmosphere, the more water vapor it will entrap as water evaporates from Earth’s surface. The Sun’s ultraviolet rays will break this water vapor down into oxygen and hydrogen, a gas light enough to escape.

With water escaping into space through this process, the oceans will dry up and the crust will dry out, leaving a desolate, uninhabitable world. As volcanoes continue throwing carbon dioxide into the atmosphere, there will be no oceans to swallow it or life forms to store it. This buildup of carbon dioxide causes what is called a “runaway greenhouse effect,” turning Earth into a hot, dry world like Venus. In fact, Venus may have once hosted a shallow liquid-water ocean and temperatures conducive to life before a runaway greenhouse process made its environment unbearable when it was as old as 2 billion years.

Aging Into Gianthood
When our Sun approaches its red giant phase some 6 billion years from now, it will run out of fuel in its core. As hydrogen fusion slows, the core once again begins to contract. As the core gets smaller, it heats up until it can kick off another round of nuclear reactions, fusing helium into heavier elements such as carbon, nitrogen, and oxygen. The hotter core also makes hydrogen fuse in the “shell” of material surrounding the core. Meanwhile, extra heat produced deep within the star causes its outer layer of gas to puff up.

The end of the red giant phase is typically the most violent time in a star’s life. The bloated, dying star throws out material from its outer layers in intense episodic bursts. In our own solar system, the Sun will puff up so much that it will melt, evaporate, and eat up some of the inner rocky planets. “I am confident that the Sun will swallow Mercury and Venus, and not Mars. But the fate of the Earth – which resides in between – is less clear,” said astronomer Dimitri Veras at the University of Warwick.

Scientists studying whether or not Earth will be both toasted and swallowed create computer models of the gravitational interactions between Earth and the Sun as the solar system ages. Recent modeling suggests Earth probably won’t make it out intact. But even if it does, all of the planets that survive will experience skyrocketing levels of energy from the expanding Sun, bathing their atmospheres and surfaces with intense radiation.

“We’ll all be long gone,” Mandell assured us. “Earth won’t be hab itable, and the only chance for survival would be for an advanced civilization to migrate to a new planetary home.”

The planets’ orbits may also become unstable. As the red giant loses mass, the star’s gravitational hold on its planets becomes much weaker, so their orbits will expand. In our own solar system, the Sun will throw off about half its mass, so the outer planets’ orbits will drift outward, settling twice as far as they are today. Neptune, at 30 times the Earth-Sun distance, will eventually hike out to about 60 times the Earth-Sun distance. Approaching the end of its fuel-burning life, the Sun will become much brighter and bigger. It will grow so large in diameter that it could fill the entire sky from the surface of a surviving planet.

NEWS FLASH: Heating up frozen worlds
Life as we know it requires liquid water, and a rocky planet needs a certain amount of starlight so that any available water won’t evaporate away or freeze. If scientists know enough about a star and its planet, they can calculate whether the planet could indeed harbor liquid water, meaning the star would be in the “habitable zone.”

But habitability of planets changes as a star gets older. A 2016 study led by Ramses M. Ramirez of Cornell University looked at different stars and predicted what would happen to their planets over time. Frozen planets, too cold to host liquid water when their star resembles our present-day Sun, may thaw out when their star expands into a red giant, because they will receive so much more heat energy.

“In the far future, such worlds could become habitable around small red suns for billions of years, maybe even starting life, just like Earth,” said study co-author Lisa Kaltnegger of Cornell. “That makes me very optimistic for the chances for life in the long run.”

When the core of the former red giant has exhausted all of its fuel and shed all the gas it can, the remaining dense stellar cinder is called a white dwarf. The white dwarf is considered “dead” because atoms inside of it no longer fuse to give the star energy. But it still “shines” because it is so hot. Eventually, it will cool off and fade from view. Our Sun will reach this death about 8 billion years from now.

Observations of dusty debris belts around white dwarfs suggest that giant planets may hold small bodies in orbit around a white dwarf, and even fling them inward, to be chewed up by the dead star. This idea took root because of a variety of heavy elements detected in the atmospheres of white dwarfs – so heavy that they should have sunk into the dense, dead star long ago.

Almost every star in the universe eventually goes through this transition from red giant to white dwarf, although extremely low-mass stars will take longer than the present age of the universe to get there. However, if a star is extremely massive, it could follow a different path, expanding into a supergiant star and ultimately exploding as a supernova.

Can planets be born in a supernova?
Yes! The unimaginably violent explosion of a supernova can trigger a whole new generation of stars, as well as planets. In fact, the first planets ever discovered outside our solar system are orbiting a pulsar, the crushingly dense remnant of a supernova that spins and pulses like a lighthouse. PSR B1257+12, discovered with the Arecibo radio telescope in Puerto Rico in 1992, hosts three planets. These planets would not have survived their star’s explosion. So they must have been created in the aftermath as debris formed a swirling cloud of gas and dust around the pulsar.

On the Shoulders of Supergiants
Supergiant stars contain many layers of different kinds of atoms fusing, creating an enormous output of energy. To date, no planets have been found around supergiant stars that will explode one day. That doesn’t mean they aren’t there, however. Supergiant stars are very rare, and so bright that they would far outshine any orbiting bodies. It is possible that our technology is not yet advanced enough to find their planets.

Supergiants may be fleeting, but their explosions play an important role in this story. The shock wave from the supernova can trigger the formation of new stars, birthing new lives in the wake of death.

NEWS FLASH: Buried exoplanet treasure
In 1917, astronomer Adriaan van Maanen discovered what appeared to be a faint, fast-moving star. The same year, Walter Sydney Adams captured the star’s spectrum – a chemical fingerprint. Little did they know that they had captured the very first evidence of a white dwarf surrounded by planetary debris – and perhaps even the first indication of the existence of exoplanets.

The spectrum of the star showed calcium and other heavy elements, meaning the white dwarf had gobbled up material with these components relatively recently. The leading theory is that exoplanets could fling small rocky bodies toward the white dwarf, where they would be pulverized by the dead star’s gravity.

Today we call these dead stars with heavy elements in their photospheres “polluted white dwarfs.” NASA’s Spitzer Space Telescope has confirmed that about 40 white dwarfs have hot, dusty disks. Another handful emerged in data from NASA’s Wide-field Infrared Survey Explorer (WISE). More than a century after Adams’ spectrum, the puzzle pieces are still coming together: In 2015, astronomers using NASA’s Kepler Space Telescope made the first discovery of a minor planet transiting a white dwarf, and in 2017 a different group found evidence of a white dwarf snacking on a possible comet-like body.
"`

module.exports = { CONTEXT };